language: go

go:
- "1.11.x"

os:
- linux
- osx

env:
- GO111MODULE=on

services:
- mysql

# default install is: go get -t ./...
install: 
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew update > /dev/null;
    brew install mysql@5.7;
    export PATH="/usr/local/opt/mysql@5.7/bin:$PATH";
    mysql.server start;
  fi

before_script:
- mysql -u root -e 'CREATE DATABASE test;'

# default script is: go test -v ./...
script:
# test base
- cd base/tests && go test && cd ../..

# test httpclient
- cd httpclient/tests && go test && cd ../..

# test discover, "base_test.go:37: node is nil"
# - cd discover/tests && go test && cd ../..

# test db, use travis mysql service
- cd db/tests && go test && cd ../..

# test redis, not mock
#- cd redis/tests && go test && cd ../..

# test s
- cd tests && go test && cd ..

# test all, not support for indenpancy tests directory
# - go test -v ./...
